var countries_json = {
      "" : { title: "Not Specified", empty: true },
      "US" : { title: "United States" },
      "CA" : { title: "Canada" },
      "AF" : { title: "Afghanistan" },
      "AL" : { title: "Albania" },
      "DZ" : { title: "Algeria" },
      "AS" : { title: "American Samoa" },
      "AD" : { title: "Andorra" },
      "AO" : { title: "Angola" },
      "AI" : { title: "Anguilla" },
      "AQ" : { title: "Antarctica" },
      "AG" : { title: "Antigua and Barbuda" },
      "AR" : { title: "Argentina" },
      "AM" : { title: "Armenia" },
      "AW" : { title: "Aruba" },
      "AU" : { title: "Australia" },
      "AT" : { title: "Austria" },
      "AZ" : { title: "Azerbaijan" },
      "BS" : { title: "Bahamas" },
      "BH" : { title: "Bahrain" },
      "BD" : { title: "Bangladesh" },
      "BB" : { title: "Barbados" },
      "BY" : { title: "Belarus" },
      "BE" : { title: "Belgium" },
      "BZ" : { title: "Belize" },
      "BJ" : { title: "Benin" },
      "BM" : { title: "Bermuda" },
      "BT" : { title: "Bhutan" },
      "BO" : { title: "Bolivia" },
      "BA" : { title: "Bosnia and Herzegovina" },
      "BW" : { title: "Botswana" },
      "BV" : { title: "Bouvet Island" },
      "BR" : { title: "Brazil" },
      "IO" : { title: "British Indian Ocean Territory" },
      "BN" : { title: "Brunei Darussalam" },
      "BG" : { title: "Bulgaria" },
      "BF" : { title: "Burkina Faso" },
      "BI" : { title: "Burundi" },
      "KH" : { title: "Cambodia" },
      "CM" : { title: "Cameroon" },
      "CV" : { title: "Cape Verde" },
      "KY" : { title: "Cayman Islands" },
      "CF" : { title: "Central African Republic" },
      "TD" : { title: "Chad" },
      "CL" : { title: "Chile" },
      "CN" : { title: "China" },
      "CX" : { title: "Christmas Island" },
      "CC" : { title: "Cocos (Keeling) Islands" },
      "CO" : { title: "Colombia" },
      "KM" : { title: "Comoros" },
      "CG" : { title: "Congo" },
      "CK" : { title: "Cook Islands" },
      "CR" : { title: "Costa Rica" },
      "HR" : { title: "Croatia (Hrvatska)" },
      "CU" : { title: "Cuba" },
      "CY" : { title: "Cyprus" },
      "CZ" : { title: "Czech Republic" },
      "CS" : { title: "Czechoslovakia (former)" },
      "DK" : { title: "Denmark" },
      "DJ" : { title: "Djibouti" },
      "DM" : { title: "Dominica" },
      "DO" : { title: "Dominican Republic" },
      "TP" : { title: "East Timor" },
      "EC" : { title: "Ecuador" },
      "EG" : { title: "Egypt" },
      "SV" : { title: "El Salvador" },
      "GQ" : { title: "Equatorial Guinea" },
      "ER" : { title: "Eritrea" },
      "EE" : { title: "Estonia" },
      "ET" : { title: "Ethiopia" },
      "FK" : { title: "Falkland Islands (Malvinas)" },
      "FO" : { title: "Faroe Islands" },
      "FJ" : { title: "Fiji" },
      "FI" : { title: "Finland" },
      "FR" : { title: "France" },
      "FX" : { title: "France, Metropolitan" },
      "GF" : { title: "French Guiana" },
      "PF" : { title: "French Polynesia" },
      "TF" : { title: "French Southern Territories" },
      "GA" : { title: "Gabon" },
      "GM" : { title: "Gambia" },
      "GE" : { title: "Georgia" },
      "DE" : { title: "Germany" },
      "GH" : { title: "Ghana" },
      "GI" : { title: "Gibraltar" },
      "GR" : { title: "Greece" },
      "GL" : { title: "Greenland" },
      "GD" : { title: "Grenada" },
      "GP" : { title: "Guadeloupe" },
      "GU" : { title: "Guam" },
      "GT" : { title: "Guatemala" },
      "GN" : { title: "Guinea" },
      "GW" : { title: "Guinea-Bissau" },
      "GY" : { title: "Guyana" },
      "HT" : { title: "Haiti" },
      "HM" : { title: "Heard and McDonald Islands" },
      "HN" : { title: "Honduras" },
      "HK" : { title: "Hong Kong" },
      "HU" : { title: "Hungary" },
      "IS" : { title: "Iceland" },
      "IN" : { title: "India" },
      "ID" : { title: "Indonesia" },
      "IR" : { title: "Iran" },
      "IQ" : { title: "Iraq" },
      "IE" : { title: "Ireland" },
      "IL" : { title: "Israel" },
      "IT" : { title: "Italy" },
      "JM" : { title: "Jamaica" },
      "JP" : { title: "Japan" },
      "JO" : { title: "Jordan" },
      "KZ" : { title: "Kazakhstan" },
      "KE" : { title: "Kenya" },
      "KI" : { title: "Kiribati" },
      "KP" : { title: "Korea (North)" },
      "KR" : { title: "Korea (South)" },
      "KW" : { title: "Kuwait" },
      "KG" : { title: "Kyrgyzstan" },
      "LA" : { title: "Laos" },
      "LV" : { title: "Latvia" },
      "LB" : { title: "Lebanon" },
      "LS" : { title: "Lesotho" },
      "LR" : { title: "Liberia" },
      "LY" : { title: "Libya" },
      "LI" : { title: "Liechtenstein" },
      "LT" : { title: "Lithuania" },
      "LU" : { title: "Luxembourg" },
      "MO" : { title: "Macau" },
      "MK" : { title: "Macedonia" },
      "MG" : { title: "Madagascar" },
      "MW" : { title: "Malawi" },
      "MY" : { title: "Malaysia" },
      "MV" : { title: "Maldives" },
      "ML" : { title: "Mali" },
      "MT" : { title: "Malta" },
      "MH" : { title: "Marshall Islands" },
      "MQ" : { title: "Martinique" },
      "MR" : { title: "Mauritania" },
      "MU" : { title: "Mauritius" },
      "YT" : { title: "Mayotte" },
      "MX" : { title: "Mexico" },
      "FM" : { title: "Micronesia" },
      "MD" : { title: "Moldova" },
      "MC" : { title: "Monaco" },
      "MN" : { title: "Mongolia" },
      "ME" : { title: "Montenegro" },
      "MS" : { title: "Montserrat" },
      "MA" : { title: "Morocco" },
      "MZ" : { title: "Mozambique" },
      "MM" : { title: "Myanmar" },
      "NA" : { title: "Namibia" },
      "NR" : { title: "Nauru" },
      "NP" : { title: "Nepal" },
      "NL" : { title: "Netherlands" },
      "AN" : { title: "Netherlands Antilles" },
      "NT" : { title: "Neutral Zone" },
      "NC" : { title: "New Caledonia" },
      "NZ" : { title: "New Zealand (Aotearoa)" },
      "NI" : { title: "Nicaragua" },
      "NE" : { title: "Niger" },
      "NG" : { title: "Nigeria" },
      "NU" : { title: "Niue" },
      "NF" : { title: "Norfolk Island" },
      "MP" : { title: "Northern Mariana Islands" },
      "NO" : { title: "Norway" },
      "OM" : { title: "Oman" },
      "PK" : { title: "Pakistan" },
      "PW" : { title: "Palau" },
      "PA" : { title: "Panama" },
      "PG" : { title: "Papua New Guinea" },
      "PY" : { title: "Paraguay" },
      "PE" : { title: "Peru" },
      "PH" : { title: "Philippines" },
      "PN" : { title: "Pitcairn" },
      "PL" : { title: "Poland" },
      "PT" : { title: "Portugal" },
      "PR" : { title: "Puerto Rico" },
      "QA" : { title: "Qatar" },
      "RE" : { title: "Reunion" },
      "RO" : { title: "Romania" },
      "RU" : { title: "Russian Federation" },
      "RW" : { title: "Rwanda" },
      "GS" : { title: "S. Georgia and S. Sandwich Isls." },
      "KN" : { title: "Saint Kitts and Nevis" },
      "LC" : { title: "Saint Lucia" },
      "VC" : { title: "Saint Vincent and the Grenadines" },
      "WS" : { title: "Samoa" },
      "SM" : { title: "San Marino" },
      "ST" : { title: "Sao Tome and Principe" },
      "SA" : { title: "Saudi Arabia" },
      "SN" : { title: "Senegal" },
      "RS" : { title: "Serbia" },
      "SC" : { title: "Seychelles" },
      "SL" : { title: "Sierra Leone" },
      "SG" : { title: "Singapore" },
      "SK" : { title: "Slovak Republic" },
      "SI" : { title: "Slovenia" },
      "Sb" : { title: "Solomon Islands" },
      "SO" : { title: "Somalia" },
      "ZA" : { title: "South Africa" },
      "ES" : { title: "Spain" },
      "LK" : { title: "Sri Lanka" },
      "SH" : { title: "St. Helena" },
      "PM" : { title: "St. Pierre and Miquelon" },
      "SD" : { title: "Sudan" },
      "SR" : { title: "Suriname" },
      "SJ" : { title: "Svalbard and Jan Mayen Islands" },
      "SZ" : { title: "Swaziland" },
      "SE" : { title: "Sweden" },
      "CH" : { title: "Switzerland" },
      "SY" : { title: "Syria" },
      "TW" : { title: "Taiwan" },
      "TJ" : { title: "Tajikistan" },
      "TZ" : { title: "Tanzania" },
      "TH" : { title: "Thailand" },
      "TG" : { title: "Togo" },
      "TK" : { title: "Tokelau" },
      "TO" : { title: "Tonga" },
      "TT" : { title: "Trinidad and Tobago" },
      "TN" : { title: "Tunisia" },
      "TR" : { title: "Turkey" },
      "TM" : { title: "Turkmenistan" },
      "TC" : { title: "Turks and Caicos Islands" },
      "TV" : { title: "Tuvalu" },
      "UM" : { title: "US Minor Outlying Islands" },
      "UG" : { title: "Uganda" },
      "UA" : { title: "Ukraine" },
      "AE" : { title: "United Arab Emirates" },
      "GB" : { title: "United Kingdom" },
      "UY" : { title: "Uruguay" },
      "UZ" : { title: "Uzbekistan" },
      "VU" : { title: "Vanuatu" },
      "VA" : { title: "Vatican City State (Holy See)" },
      "VE" : { title: "Venezuela" },
      "VN" : { title: "Viet Nam" },
      "VG" : { title: "Virgin Islands (British)" },
      "VI" : { title: "Virgin Islands (U.S.)" },
      "WF" : { title: "Wallis and Futuna Islands" },
      "EH" : { title: "Western Sahara" },
      "YE" : { title: "Yemen" },
      "YU" : { title: "Yugoslavia" },
      "ZR" : { title: "Zaire" },
      "ZM" : { title: "Zambia" },
      "ZW" : { title: "Zimbabwe" }
  }